language: python

python:
  - 3.6

cache: pip

install:
  - pip install --upgrade pip
  - pip install -U scikit-learn
  - pip install --progress-bar off -e .[develop]
  - pip install sphinx

script:
  # - python setup.py test
  - cd docs && rm source/tatk.*.rst
  - sphinx-apidoc -o ./source ../tatk/
  - cd source && python gen_rst.py --project tatk && cd ..
  - make html
  - mv ./build/html ./build/docs && rm -r ./build/doctrees && mv LICENSE.txt ./build && mv README.md ./build && cd ..
  
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $DEPLOY_KEY
    keep-history: true
    repo: thu-coai/tatk_docs
    target-branch: master
    local-dir: ./docs/build
    on:
      branch: master
  - provider: script
    skip-cleanup: true
    script: coveralls
    on:
      all_branches: true
      condition: true
